# -*- coding: utf-8 -*-
"""ModeloA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GyGLpPGI2MXoHwC7ZUSAAkHA_36iiaeo
"""

import streamlit as st
import pickle
import numpy as np
import pandas as pd

# ── Cargar modelo
with open('modelo-class.pkl', 'rb') as f:
    modelNN, labelencoder, variables, scaler = pickle.load(f)

# ── Configuración de la página
st.set_page_config(
    page_title="Viabilidad de Tokenización Inmobiliaria",
    page_icon="🏗️",
    layout="centered"
)

st.title("🏗️ Viabilidad de Tokenización Inmobiliaria")
st.markdown("**Antioquia, Colombia** — Modelo de clasificación basado en datos CEED-DANE 2020–2025")
st.markdown("---")
st.markdown("Complete las características del proyecto para evaluar su viabilidad de inversión.")

# ── Formulario de entrada
col1, col2 = st.columns(2)

with col1:
    st.subheader("💰 Precio y valor")

    PRECIOVTAX = st.number_input(
        "Precio por m² (miles COP)",
        min_value=100,
        max_value=9400,
        value=2500,
        step=100,
        help="Precio de venta por metro cuadrado en miles de COP"
    )

    TIPOVRDEST = st.selectbox(
        "Tipo de valor del destino",
        options=[1, 2],
        format_func=lambda x: "Real" if x == 1 else "Estimado",
        help="Indica si el precio es un valor real o estimado"
    )

    st.subheader("🏢 Perfil del proyecto")

    ESTRATO = st.selectbox(
        "Estrato socioeconómico",
        options=[1, 2, 3, 4, 5, 6],
        index=2,
        help="Estrato del proyecto (1=bajo, 6=alto)"
    )

    RANVIVI = st.selectbox(
        "Rango de precio de vivienda",
        options=[1, 2, 3, 4, 5, 6],
        format_func=lambda x: {
            1: "VIP (hasta 70 SMMLV)",
            2: "VIS (70-135 SMMLV)",
            3: "No VIS bajo (135-235 SMMLV)",
            4: "No VIS medio (235-435 SMMLV)",
            5: "No VIS alto (435-1000 SMMLV)",
            6: "Premium (más de 1000 SMMLV)"
        }[x],
        index=2
    )

with col2:
    st.subheader("🔨 Avance de obra")

    CAPITULO = st.selectbox(
        "Capítulo actual de obra",
        options=[1, 2, 3, 4, 5, 6],
        format_func=lambda x: {
            1: "Capítulo 1 - Cimentación",
            2: "Capítulo 2 - Estructura",
            3: "Capítulo 3 - Mampostería",
            4: "Capítulo 4 - Acabados",
            5: "Capítulo 5 - Instalaciones",
            6: "Capítulo 6 - Remates"
        }[x],
        index=2
    )

    GRADOAVANC = st.slider(
        "Grado de avance (%)",
        min_value=1,
        max_value=100,
        value=50,
        help="Porcentaje de avance actual de la obra"
    )

    st.subheader("📋 Formalidad")

    OB_FORMAL = st.selectbox(
        "Formalidad de la obra",
        options=[1, 2],
        format_func=lambda x: "Formal" if x == 1 else "Informal",
        help="Indica si la obra tiene licencia y cumple requisitos legales"
    )

    AMPLIACION = st.selectbox(
        "¿Es una ampliación?",
        options=[1, 2],
        format_func=lambda x: "Sí es ampliación" if x == 1 else "No es ampliación",
        index=1
    )

st.markdown("---")
if st.button("🔍 Evaluar viabilidad del proyecto", use_container_width=True):

    # 1. Crear un diccionario con todas las variables inicializadas en 0.0
    # Es vital que sean flotantes (0.0) para que coincidan con el entrenamiento
    fila = {col: 0.0 for col in variables}

    # 2. Asignar valores a las variables numéricas directas
    # NOTA: Solo asigna las que el modelo realmente espera (las que están en 'variables')
    if 'PRECIOVTAX' in fila: fila['PRECIOVTAX'] = float(PRECIOVTAX)
    if 'ESTRATO' in fila:    fila['ESTRATO'] = float(ESTRATO)
    if 'RANVIVI' in fila:    fila['RANVIVI'] = float(RANVIVI)
    if 'CAPITULO' in fila:   fila['CAPITULO'] = float(CAPITULO)

    # 3. Activar Dummies con el formato exacto del Colab (usando .0)
    # TIPOVRDEST
    cat_tipovr = f'TIPOVRDEST_{float(TIPOVRDEST)}'
    if cat_tipovr in fila: fila[cat_tipovr] = 1.0

    # OB_FORMAL
    cat_formal = f'OB_FORMAL_{float(OB_FORMAL)}'
    if cat_formal in fila: fila[cat_formal] = 1.0

    # AMPLIACION
    cat_ampli = f'AMPLIACION_{float(AMPLIACION)}'
    if cat_ampli in fila: fila[cat_ampli] = 1.0

    # 4. Crear DataFrame y REORDENAR columnas según 'variables'
    # El orden es sagrado para el Scaler y la Red Neuronal
    entrada = pd.DataFrame([fila])[variables]

    # 5. Escalar y Predecir
    try:
        entrada_scaled = scaler.transform(entrada)
        pred = modelNN.predict(entrada_scaled)[0]
        prob = modelNN.predict_proba(entrada_scaled)[0]
        
        # ... aquí sigue tu código para mostrar resultados (st.success / st.error) ...
    except ValueError as e:
        st.error(f"Error de consistencia de datos: {e}")
    
    # ── Mostrar resultado
    st.markdown("## Resultado")

    if pred == 1:
        st.success(f"✅ **PROYECTO VIABLE** para tokenización")
        st.metric(
            label="Probabilidad de viabilidad",
            value=f"{prob[1]*100:.1f}%"
        )
        st.markdown("""
        **Interpretación:** El modelo clasifica este proyecto como viable
        para esquemas de tokenización inmobiliaria en Antioquia.
        Las características ingresadas son consistentes con proyectos
        que históricamente han sido completados exitosamente.
        """)
    else:
        st.error(f"❌ **PROYECTO NO VIABLE** para tokenización")
        st.metric(
            label="Probabilidad de no viabilidad",
            value=f"{prob[0]*100:.1f}%"
        )
        st.markdown("""
        **Interpretación:** El modelo clasifica este proyecto como no viable
        para esquemas de tokenización inmobiliaria en Antioquia.
        Las características ingresadas son consistentes con proyectos
        que históricamente han presentado paralizaciones o suspensiones.
        """)

    # Detalle de probabilidades
    st.markdown("### Detalle de probabilidades")
    col_a, col_b = st.columns(2)
    col_a.metric("No viable (0)", f"{prob[0]*100:.1f}%")
    col_b.metric("Viable (1)", f"{prob[1]*100:.1f}%")

st.markdown("---")
st.caption("Modelo desarrollado con datos CEED-DANE 2020–2025 | Maestría en Ciencia de Datos | Tokenización Inmobiliaria Antioquia")
